"""empty message

Revision ID: 1863efc72f62
Revises: 029cff91ee6d
Create Date: 2019-10-22 21:15:51.729160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1863efc72f62'
down_revision = '029cff91ee6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_salt', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_salt')
    # ### end Alembic commands ###
