"""empty message

Revision ID: 6c8fe1eae9dc
Revises: 5aafb52128c8
Create Date: 2019-10-09 01:59:57.221652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c8fe1eae9dc'
down_revision = '5aafb52128c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('url', 'for_download')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url', sa.Column('for_download', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
