"""empty message

Revision ID: 8cc643ccd1e2
Revises: d11aa37aeb0f
Create Date: 2019-10-09 02:16:36.907272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cc643ccd1e2'
down_revision = 'd11aa37aeb0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movie', 'age_restrictions',
               existing_type=sa.SMALLINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movie', 'age_restrictions',
               existing_type=sa.SMALLINT(),
               nullable=False)
    # ### end Alembic commands ###
