"""empty message

Revision ID: ba4ce1cb909d
Revises: db476107399c
Create Date: 2019-10-14 22:10:42.718528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba4ce1cb909d'
down_revision = 'db476107399c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_user_login'), 'user', ['login'], unique=False)
    op.drop_index('ix_user_username', table_name='user')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    op.drop_index(op.f('ix_user_login'), table_name='user')
    op.drop_column('user', 'login')
    # ### end Alembic commands ###
