"""empty message

Revision ID: d11aa37aeb0f
Revises: 6c8fe1eae9dc
Create Date: 2019-10-09 02:14:03.621871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd11aa37aeb0f'
down_revision = '6c8fe1eae9dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_country',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'country_id')
    )
    op.drop_constraint('movie_country_id_fkey', 'movie', type_='foreignkey')
    op.drop_column('movie', 'country_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('movie_country_id_fkey', 'movie', 'country', ['country_id'], ['id'])
    op.drop_table('movie_country')
    # ### end Alembic commands ###
