"""empty message

Revision ID: db476107399c
Revises: e620e5180201
Create Date: 2019-10-10 10:46:41.736978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db476107399c'
down_revision = 'e620e5180201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_role_name', table_name='role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_role_name', 'role', ['name'], unique=False)
    # ### end Alembic commands ###
